### ISSUE TITLE
Not compatible with Angular 2.2.3

### ISSUE THREAD

**Issue by tomchovanec** [vaadin/expense-manager-ng2-demo#19]
Shows empty grid. Seems like columns were not prepared properly.
Also throws exception:

core.umd.js:2837 EXCEPTION: Uncaught (in promise): TypeError: Cannot set property 'renderer' of undefined
TypeError: Cannot set property 'renderer' of undefined
    at ExpensesList.gridReady (http://localhost:3000/app/expenses-list/expenses_list.component.js:42:34)
    at eval (http://localhost:3000/app/expenses-list/expenses_list.component.js:20:19)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:229:26)
    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5975:41)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:228:32)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:113:43)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:509:57
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:262:35)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5966:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:261:40)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47)
    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:405:35)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:336:25)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1149:25)

// package.json

```
"dependencies": {
    "@angular/common":  "2.2.3",
    "@angular/compiler":  "2.2.3",
    "@angular/core":  "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http":  "2.2.3",
    "@angular/platform-browser":  "2.2.3",
    "@angular/platform-browser-dynamic":  "2.2.3",
    "@angular/router":  "3.2.3",
    "@angular/upgrade":  "2.2.3",

    "systemjs": "0.19.41",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-rc.4",
    "zone.js": "^0.7.2",

    "angular2-in-memory-web-api": "0.0.21",
    "bootstrap": "^3.3.7",
    "@vaadin/angular2-polymer": "1.0.0-beta5"
  },

```

**Comment by samiheikki** [comment]
Thanks for the info @tomchovanec. This issue and a workaround is described in https://github.com/vaadin/angular2-polymer/issues/104
